version: '3.8'

services:
  database:
    container_name: pg_nextjs
    image: 'postgres:latest'
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pgadmin4_nextjs
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/

networks:
  postgres-network:
    driver: bridge
